name: ðŸš€ Deploy to Google VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ§± Checkout code
        uses: actions/checkout@v4

      - name: âš™ï¸ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: ðŸ”‘ Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: ðŸš€ Deploy code to server
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd /var/www/html/new/MERN-Admin-Panel
            git pull origin main
            cd FrontEnd
            npm install
            npm run build
            cd ../BackEnd
            npm install
            pm2 restart backend --update-env
            sudo systemctl reload nginx
          EOF
